[placeholders.component_outdir]
prompt = "Where to output your WASI component"
default = "target/server"

[template]
# Files to include in the template but exclude from variable substitution
exclude = [
    "**/*.ico",
]